#nullable disable
namespace DesktopAdmin.Forms;

partial class AdminDashboardForm
{
    private System.ComponentModel.IContainer components = null;
    private Label lblWelcome;
    private TabControl tabMain;
    private TabPage tabJobs;
    private TabPage tabApplications;
    private TabPage tabReports;
    private DataGridView dgvJobs;
    private DataGridView dgvApplications;
    private Button btnAddJob;
    private Button btnEditJob;
    private Button btnDeleteJob;
    private Button btnAccept;
    private Button btnReject;
    private Button btnMarkPending;
    private Button btnRefreshReports;
    private Label lblTotalStudents;
    private Label lblActiveJobs;
    private Label lblTotalApplications;
    private Label lblAccepted;
    private Label lblRejected;
    private Label lblPending;
    private Label lblTotalStudentsValue;
    private Label lblActiveJobsValue;
    private Label lblTotalApplicationsValue;
    private Label lblAcceptedValue;
    private Label lblRejectedValue;
    private Label lblPendingValue;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components is not null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        lblWelcome = new Label();
        tabMain = new TabControl();
        tabJobs = new TabPage();
        btnDeleteJob = new Button();
        btnEditJob = new Button();
        btnAddJob = new Button();
        dgvJobs = new DataGridView();
        tabApplications = new TabPage();
        btnMarkPending = new Button();
        btnReject = new Button();
        btnAccept = new Button();
        dgvApplications = new DataGridView();
        tabReports = new TabPage();
        btnRefreshReports = new Button();
        lblPendingValue = new Label();
        lblRejectedValue = new Label();
        lblAcceptedValue = new Label();
        lblTotalApplicationsValue = new Label();
        lblActiveJobsValue = new Label();
        lblTotalStudentsValue = new Label();
        lblPending = new Label();
        lblRejected = new Label();
        lblAccepted = new Label();
        lblTotalApplications = new Label();
        lblActiveJobs = new Label();
        lblTotalStudents = new Label();
        tabMain.SuspendLayout();
        tabJobs.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvJobs).BeginInit();
        tabApplications.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvApplications).BeginInit();
        tabReports.SuspendLayout();
        SuspendLayout();
        BackColor = Color.FromArgb(243, 246, 252);
        Font = new Font("Segoe UI", 9F);
        lblWelcome.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblWelcome.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblWelcome.ForeColor = Color.FromArgb(77, 88, 110);
        lblWelcome.Location = new Point(578, 18);
        lblWelcome.Name = "lblWelcome";
        lblWelcome.Size = new Size(287, 23);
        lblWelcome.TabIndex = 0;
        lblWelcome.TextAlign = ContentAlignment.MiddleRight;
        tabMain.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        tabMain.Appearance = TabAppearance.FlatButtons;
        tabMain.Controls.Add(tabJobs);
        tabMain.Controls.Add(tabApplications);
        tabMain.Controls.Add(tabReports);
        tabMain.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        tabMain.ItemSize = new Size(120, 34);
        tabMain.Location = new Point(12, 54);
        tabMain.Name = "tabMain";
        tabMain.SelectedIndex = 0;
        tabMain.Size = new Size(853, 525);
        tabMain.SizeMode = TabSizeMode.Fixed;
        tabMain.TabIndex = 1;
        tabJobs.BackColor = Color.FromArgb(250, 252, 255);
        tabJobs.Controls.Add(btnDeleteJob);
        tabJobs.Controls.Add(btnEditJob);
        tabJobs.Controls.Add(btnAddJob);
        tabJobs.Controls.Add(dgvJobs);
        tabJobs.Location = new Point(4, 38);
        tabJobs.Name = "tabJobs";
        tabJobs.Padding = new Padding(3);
        tabJobs.Size = new Size(845, 483);
        tabJobs.TabIndex = 0;
        tabJobs.Text = "Jobs";
        btnDeleteJob.BackColor = Color.FromArgb(210, 76, 70);
        btnDeleteJob.Cursor = Cursors.Hand;
        btnDeleteJob.FlatAppearance.BorderSize = 0;
        btnDeleteJob.FlatStyle = FlatStyle.Flat;
        btnDeleteJob.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnDeleteJob.ForeColor = Color.White;
        btnDeleteJob.Location = new Point(272, 18);
        btnDeleteJob.Name = "btnDeleteJob";
        btnDeleteJob.Size = new Size(118, 36);
        btnDeleteJob.TabIndex = 3;
        btnDeleteJob.Text = "Delete";
        btnDeleteJob.UseVisualStyleBackColor = false;
        btnDeleteJob.Click += btnDeleteJob_Click;
        btnEditJob.BackColor = Color.White;
        btnEditJob.Cursor = Cursors.Hand;
        btnEditJob.FlatAppearance.BorderColor = Color.FromArgb(186, 196, 214);
        btnEditJob.FlatStyle = FlatStyle.Flat;
        btnEditJob.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnEditJob.ForeColor = Color.FromArgb(52, 64, 92);
        btnEditJob.Location = new Point(145, 18);
        btnEditJob.Name = "btnEditJob";
        btnEditJob.Size = new Size(118, 36);
        btnEditJob.TabIndex = 2;
        btnEditJob.Text = "Edit";
        btnEditJob.UseVisualStyleBackColor = false;
        btnEditJob.Click += btnEditJob_Click;
        btnAddJob.BackColor = Color.FromArgb(31, 119, 90);
        btnAddJob.Cursor = Cursors.Hand;
        btnAddJob.FlatAppearance.BorderSize = 0;
        btnAddJob.FlatStyle = FlatStyle.Flat;
        btnAddJob.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnAddJob.ForeColor = Color.White;
        btnAddJob.Location = new Point(18, 18);
        btnAddJob.Name = "btnAddJob";
        btnAddJob.Size = new Size(118, 36);
        btnAddJob.TabIndex = 1;
        btnAddJob.Text = "Add Job";
        btnAddJob.UseVisualStyleBackColor = false;
        btnAddJob.Click += btnAddJob_Click;
        dgvJobs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvJobs.BackgroundColor = Color.White;
        dgvJobs.BorderStyle = BorderStyle.None;
        dgvJobs.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvJobs.Location = new Point(18, 72);
        dgvJobs.MultiSelect = false;
        dgvJobs.Name = "dgvJobs";
        dgvJobs.ReadOnly = true;
        dgvJobs.RowHeadersWidth = 51;
        dgvJobs.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvJobs.Size = new Size(809, 394);
        dgvJobs.TabIndex = 0;
        tabApplications.BackColor = Color.FromArgb(250, 252, 255);
        tabApplications.Controls.Add(btnMarkPending);
        tabApplications.Controls.Add(btnReject);
        tabApplications.Controls.Add(btnAccept);
        tabApplications.Controls.Add(dgvApplications);
        tabApplications.Location = new Point(4, 38);
        tabApplications.Name = "tabApplications";
        tabApplications.Padding = new Padding(3);
        tabApplications.Size = new Size(845, 483);
        tabApplications.TabIndex = 1;
        tabApplications.Text = "Applications";
        btnMarkPending.BackColor = Color.White;
        btnMarkPending.Cursor = Cursors.Hand;
        btnMarkPending.FlatAppearance.BorderColor = Color.FromArgb(199, 208, 225);
        btnMarkPending.FlatStyle = FlatStyle.Flat;
        btnMarkPending.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnMarkPending.ForeColor = Color.FromArgb(87, 97, 122);
        btnMarkPending.Location = new Point(270, 18);
        btnMarkPending.Name = "btnMarkPending";
        btnMarkPending.Size = new Size(125, 36);
        btnMarkPending.TabIndex = 3;
        btnMarkPending.Text = "Mark Pending";
        btnMarkPending.UseVisualStyleBackColor = false;
        btnMarkPending.Click += btnMarkPending_Click;
        btnReject.BackColor = Color.FromArgb(210, 76, 70);
        btnReject.Cursor = Cursors.Hand;
        btnReject.FlatAppearance.BorderSize = 0;
        btnReject.FlatStyle = FlatStyle.Flat;
        btnReject.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnReject.ForeColor = Color.White;
        btnReject.Location = new Point(141, 18);
        btnReject.Name = "btnReject";
        btnReject.Size = new Size(123, 36);
        btnReject.TabIndex = 2;
        btnReject.Text = "Reject";
        btnReject.UseVisualStyleBackColor = false;
        btnReject.Click += btnReject_Click;
        btnAccept.BackColor = Color.FromArgb(31, 119, 90);
        btnAccept.Cursor = Cursors.Hand;
        btnAccept.FlatAppearance.BorderSize = 0;
        btnAccept.FlatStyle = FlatStyle.Flat;
        btnAccept.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnAccept.ForeColor = Color.White;
        btnAccept.Location = new Point(12, 18);
        btnAccept.Name = "btnAccept";
        btnAccept.Size = new Size(123, 36);
        btnAccept.TabIndex = 1;
        btnAccept.Text = "Accept";
        btnAccept.UseVisualStyleBackColor = false;
        btnAccept.Click += btnAccept_Click;
        dgvApplications.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvApplications.BackgroundColor = Color.White;
        dgvApplications.BorderStyle = BorderStyle.None;
        dgvApplications.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvApplications.Location = new Point(12, 72);
        dgvApplications.MultiSelect = false;
        dgvApplications.Name = "dgvApplications";
        dgvApplications.ReadOnly = true;
        dgvApplications.RowHeadersWidth = 51;
        dgvApplications.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvApplications.Size = new Size(815, 394);
        dgvApplications.TabIndex = 0;
        tabReports.BackColor = Color.FromArgb(250, 252, 255);
        tabReports.Controls.Add(btnRefreshReports);
        tabReports.Controls.Add(lblPendingValue);
        tabReports.Controls.Add(lblRejectedValue);
        tabReports.Controls.Add(lblAcceptedValue);
        tabReports.Controls.Add(lblTotalApplicationsValue);
        tabReports.Controls.Add(lblActiveJobsValue);
        tabReports.Controls.Add(lblTotalStudentsValue);
        tabReports.Controls.Add(lblPending);
        tabReports.Controls.Add(lblRejected);
        tabReports.Controls.Add(lblAccepted);
        tabReports.Controls.Add(lblTotalApplications);
        tabReports.Controls.Add(lblActiveJobs);
        tabReports.Controls.Add(lblTotalStudents);
        tabReports.Location = new Point(4, 38);
        tabReports.Name = "tabReports";
        tabReports.Padding = new Padding(3);
        tabReports.Size = new Size(845, 483);
        tabReports.TabIndex = 2;
        tabReports.Text = "Reports";
        btnRefreshReports.BackColor = Color.FromArgb(26, 115, 232);
        btnRefreshReports.Cursor = Cursors.Hand;
        btnRefreshReports.FlatAppearance.BorderSize = 0;
        btnRefreshReports.FlatStyle = FlatStyle.Flat;
        btnRefreshReports.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnRefreshReports.ForeColor = Color.White;
        btnRefreshReports.Location = new Point(26, 318);
        btnRefreshReports.Name = "btnRefreshReports";
        btnRefreshReports.Size = new Size(148, 40);
        btnRefreshReports.TabIndex = 12;
        btnRefreshReports.Text = "Refresh";
        btnRefreshReports.UseVisualStyleBackColor = false;
        btnRefreshReports.Click += btnRefreshReports_Click;
        lblPendingValue.AutoSize = true;
        lblPendingValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblPendingValue.ForeColor = Color.FromArgb(128, 90, 24);
        lblPendingValue.Location = new Point(308, 252);
        lblPendingValue.Name = "lblPendingValue";
        lblPendingValue.Size = new Size(31, 37);
        lblPendingValue.TabIndex = 11;
        lblPendingValue.Text = "0";
        lblRejectedValue.AutoSize = true;
        lblRejectedValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblRejectedValue.ForeColor = Color.FromArgb(187, 61, 52);
        lblRejectedValue.Location = new Point(308, 202);
        lblRejectedValue.Name = "lblRejectedValue";
        lblRejectedValue.Size = new Size(31, 37);
        lblRejectedValue.TabIndex = 10;
        lblRejectedValue.Text = "0";
        lblAcceptedValue.AutoSize = true;
        lblAcceptedValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblAcceptedValue.ForeColor = Color.FromArgb(31, 119, 90);
        lblAcceptedValue.Location = new Point(308, 152);
        lblAcceptedValue.Name = "lblAcceptedValue";
        lblAcceptedValue.Size = new Size(31, 37);
        lblAcceptedValue.TabIndex = 9;
        lblAcceptedValue.Text = "0";
        lblTotalApplicationsValue.AutoSize = true;
        lblTotalApplicationsValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblTotalApplicationsValue.ForeColor = Color.FromArgb(26, 115, 232);
        lblTotalApplicationsValue.Location = new Point(308, 102);
        lblTotalApplicationsValue.Name = "lblTotalApplicationsValue";
        lblTotalApplicationsValue.Size = new Size(31, 37);
        lblTotalApplicationsValue.TabIndex = 8;
        lblTotalApplicationsValue.Text = "0";
        lblActiveJobsValue.AutoSize = true;
        lblActiveJobsValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblActiveJobsValue.ForeColor = Color.FromArgb(32, 41, 74);
        lblActiveJobsValue.Location = new Point(308, 52);
        lblActiveJobsValue.Name = "lblActiveJobsValue";
        lblActiveJobsValue.Size = new Size(31, 37);
        lblActiveJobsValue.TabIndex = 7;
        lblActiveJobsValue.Text = "0";
        lblTotalStudentsValue.AutoSize = true;
        lblTotalStudentsValue.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblTotalStudentsValue.ForeColor = Color.FromArgb(32, 41, 74);
        lblTotalStudentsValue.Location = new Point(308, 2);
        lblTotalStudentsValue.Name = "lblTotalStudentsValue";
        lblTotalStudentsValue.Size = new Size(31, 37);
        lblTotalStudentsValue.TabIndex = 6;
        lblTotalStudentsValue.Text = "0";
        lblPending.AutoSize = true;
        lblPending.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblPending.ForeColor = Color.FromArgb(77, 88, 110);
        lblPending.Location = new Point(26, 260);
        lblPending.Name = "lblPending";
        lblPending.Size = new Size(172, 23);
        lblPending.TabIndex = 5;
        lblPending.Text = "Pending Applications";
        lblRejected.AutoSize = true;
        lblRejected.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblRejected.ForeColor = Color.FromArgb(77, 88, 110);
        lblRejected.Location = new Point(26, 210);
        lblRejected.Name = "lblRejected";
        lblRejected.Size = new Size(176, 23);
        lblRejected.TabIndex = 4;
        lblRejected.Text = "Rejected Applications";
        lblAccepted.AutoSize = true;
        lblAccepted.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblAccepted.ForeColor = Color.FromArgb(77, 88, 110);
        lblAccepted.Location = new Point(26, 160);
        lblAccepted.Name = "lblAccepted";
        lblAccepted.Size = new Size(177, 23);
        lblAccepted.TabIndex = 3;
        lblAccepted.Text = "Accepted Applications";
        lblTotalApplications.AutoSize = true;
        lblTotalApplications.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblTotalApplications.ForeColor = Color.FromArgb(77, 88, 110);
        lblTotalApplications.Location = new Point(26, 110);
        lblTotalApplications.Name = "lblTotalApplications";
        lblTotalApplications.Size = new Size(145, 23);
        lblTotalApplications.TabIndex = 2;
        lblTotalApplications.Text = "Total Applications";
        lblActiveJobs.AutoSize = true;
        lblActiveJobs.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblActiveJobs.ForeColor = Color.FromArgb(77, 88, 110);
        lblActiveJobs.Location = new Point(26, 60);
        lblActiveJobs.Name = "lblActiveJobs";
        lblActiveJobs.Size = new Size(90, 23);
        lblActiveJobs.TabIndex = 1;
        lblActiveJobs.Text = "Active Jobs";
        lblTotalStudents.AutoSize = true;
        lblTotalStudents.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        lblTotalStudents.ForeColor = Color.FromArgb(77, 88, 110);
        lblTotalStudents.Location = new Point(26, 10);
        lblTotalStudents.Name = "lblTotalStudents";
        lblTotalStudents.Size = new Size(113, 23);
        lblTotalStudents.TabIndex = 0;
        lblTotalStudents.Text = "Total Students";
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(877, 590);
        Controls.Add(tabMain);
        Controls.Add(lblWelcome);
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "AdminDashboardForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Desktop Admin Dashboard";
        tabMain.ResumeLayout(false);
        tabJobs.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvJobs).EndInit();
        tabApplications.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvApplications).EndInit();
        tabReports.ResumeLayout(false);
        tabReports.PerformLayout();
        ResumeLayout(false);
    }
}
#nullable restore
