#nullable disable
namespace DesktopAdmin.Forms;

partial class AdminDashboardForm
{
    private System.ComponentModel.IContainer components = null;
    private Label lblWelcome;
    private TabControl tabMain;
    private TabPage tabJobs;
    private TabPage tabApplications;
    private TabPage tabReports;
    private DataGridView dgvJobs;
    private DataGridView dgvApplications;
    private Button btnAddJob;
    private Button btnEditJob;
    private Button btnDeleteJob;
    private Button btnAccept;
    private Button btnReject;
    private Button btnMarkPending;
    private Button btnRefreshReports;
    private Label lblTotalStudents;
    private Label lblActiveJobs;
    private Label lblTotalApplications;
    private Label lblAccepted;
    private Label lblRejected;
    private Label lblPending;
    private Label lblTotalStudentsValue;
    private Label lblActiveJobsValue;
    private Label lblTotalApplicationsValue;
    private Label lblAcceptedValue;
    private Label lblRejectedValue;
    private Label lblPendingValue;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components is not null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        lblWelcome = new Label();
        tabMain = new TabControl();
        tabJobs = new TabPage();
        btnDeleteJob = new Button();
        btnEditJob = new Button();
        btnAddJob = new Button();
        dgvJobs = new DataGridView();
        tabApplications = new TabPage();
        btnMarkPending = new Button();
        btnReject = new Button();
        btnAccept = new Button();
        dgvApplications = new DataGridView();
        tabReports = new TabPage();
        btnRefreshReports = new Button();
        lblPendingValue = new Label();
        lblRejectedValue = new Label();
        lblAcceptedValue = new Label();
        lblTotalApplicationsValue = new Label();
        lblActiveJobsValue = new Label();
        lblTotalStudentsValue = new Label();
        lblPending = new Label();
        lblRejected = new Label();
        lblAccepted = new Label();
        lblTotalApplications = new Label();
        lblActiveJobs = new Label();
        lblTotalStudents = new Label();
        tabMain.SuspendLayout();
        tabJobs.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvJobs).BeginInit();
        tabApplications.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvApplications).BeginInit();
        tabReports.SuspendLayout();
        SuspendLayout();
        lblWelcome.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        lblWelcome.Location = new Point(578, 15);
        lblWelcome.Name = "lblWelcome";
        lblWelcome.Size = new Size(287, 23);
        lblWelcome.TabIndex = 0;
        lblWelcome.TextAlign = ContentAlignment.MiddleRight;
        tabMain.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        tabMain.Controls.Add(tabJobs);
        tabMain.Controls.Add(tabApplications);
        tabMain.Controls.Add(tabReports);
        tabMain.Location = new Point(12, 50);
        tabMain.Name = "tabMain";
        tabMain.SelectedIndex = 0;
        tabMain.Size = new Size(853, 517);
        tabMain.TabIndex = 1;
        tabJobs.Controls.Add(btnDeleteJob);
        tabJobs.Controls.Add(btnEditJob);
        tabJobs.Controls.Add(btnAddJob);
        tabJobs.Controls.Add(dgvJobs);
        tabJobs.Location = new Point(4, 29);
        tabJobs.Name = "tabJobs";
        tabJobs.Padding = new Padding(3);
        tabJobs.Size = new Size(845, 484);
        tabJobs.TabIndex = 0;
        tabJobs.Text = "Jobs";
        tabJobs.UseVisualStyleBackColor = true;
        btnDeleteJob.Location = new Point(254, 15);
        btnDeleteJob.Name = "btnDeleteJob";
        btnDeleteJob.Size = new Size(112, 34);
        btnDeleteJob.TabIndex = 3;
        btnDeleteJob.Text = "Delete";
        btnDeleteJob.UseVisualStyleBackColor = true;
        btnDeleteJob.Click += btnDeleteJob_Click;
        btnEditJob.Location = new Point(136, 15);
        btnEditJob.Name = "btnEditJob";
        btnEditJob.Size = new Size(112, 34);
        btnEditJob.TabIndex = 2;
        btnEditJob.Text = "Edit";
        btnEditJob.UseVisualStyleBackColor = true;
        btnEditJob.Click += btnEditJob_Click;
        btnAddJob.Location = new Point(18, 15);
        btnAddJob.Name = "btnAddJob";
        btnAddJob.Size = new Size(112, 34);
        btnAddJob.TabIndex = 1;
        btnAddJob.Text = "Add Job";
        btnAddJob.UseVisualStyleBackColor = true;
        btnAddJob.Click += btnAddJob_Click;
        dgvJobs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvJobs.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvJobs.Location = new Point(18, 63);
        dgvJobs.MultiSelect = false;
        dgvJobs.Name = "dgvJobs";
        dgvJobs.ReadOnly = true;
        dgvJobs.RowHeadersWidth = 51;
        dgvJobs.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvJobs.Size = new Size(809, 403);
        dgvJobs.TabIndex = 0;
        tabApplications.Controls.Add(btnMarkPending);
        tabApplications.Controls.Add(btnReject);
        tabApplications.Controls.Add(btnAccept);
        tabApplications.Controls.Add(dgvApplications);
        tabApplications.Location = new Point(4, 29);
        tabApplications.Name = "tabApplications";
        tabApplications.Padding = new Padding(3);
        tabApplications.Size = new Size(845, 484);
        tabApplications.TabIndex = 1;
        tabApplications.Text = "Applications";
        tabApplications.UseVisualStyleBackColor = true;
        btnMarkPending.Location = new Point(270, 15);
        btnMarkPending.Name = "btnMarkPending";
        btnMarkPending.Size = new Size(123, 34);
        btnMarkPending.TabIndex = 3;
        btnMarkPending.Text = "Mark Pending";
        btnMarkPending.UseVisualStyleBackColor = true;
        btnMarkPending.Click += btnMarkPending_Click;
        btnReject.Location = new Point(141, 15);
        btnReject.Name = "btnReject";
        btnReject.Size = new Size(123, 34);
        btnReject.TabIndex = 2;
        btnReject.Text = "Reject";
        btnReject.UseVisualStyleBackColor = true;
        btnReject.Click += btnReject_Click;
        btnAccept.Location = new Point(12, 15);
        btnAccept.Name = "btnAccept";
        btnAccept.Size = new Size(123, 34);
        btnAccept.TabIndex = 1;
        btnAccept.Text = "Accept";
        btnAccept.UseVisualStyleBackColor = true;
        btnAccept.Click += btnAccept_Click;
        dgvApplications.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        dgvApplications.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvApplications.Location = new Point(12, 63);
        dgvApplications.MultiSelect = false;
        dgvApplications.Name = "dgvApplications";
        dgvApplications.ReadOnly = true;
        dgvApplications.RowHeadersWidth = 51;
        dgvApplications.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvApplications.Size = new Size(815, 403);
        dgvApplications.TabIndex = 0;
        tabReports.Controls.Add(btnRefreshReports);
        tabReports.Controls.Add(lblPendingValue);
        tabReports.Controls.Add(lblRejectedValue);
        tabReports.Controls.Add(lblAcceptedValue);
        tabReports.Controls.Add(lblTotalApplicationsValue);
        tabReports.Controls.Add(lblActiveJobsValue);
        tabReports.Controls.Add(lblTotalStudentsValue);
        tabReports.Controls.Add(lblPending);
        tabReports.Controls.Add(lblRejected);
        tabReports.Controls.Add(lblAccepted);
        tabReports.Controls.Add(lblTotalApplications);
        tabReports.Controls.Add(lblActiveJobs);
        tabReports.Controls.Add(lblTotalStudents);
        tabReports.Location = new Point(4, 29);
        tabReports.Name = "tabReports";
        tabReports.Padding = new Padding(3);
        tabReports.Size = new Size(845, 484);
        tabReports.TabIndex = 2;
        tabReports.Text = "Reports";
        tabReports.UseVisualStyleBackColor = true;
        btnRefreshReports.Location = new Point(26, 292);
        btnRefreshReports.Name = "btnRefreshReports";
        btnRefreshReports.Size = new Size(135, 36);
        btnRefreshReports.TabIndex = 12;
        btnRefreshReports.Text = "Refresh";
        btnRefreshReports.UseVisualStyleBackColor = true;
        btnRefreshReports.Click += btnRefreshReports_Click;
        lblPendingValue.AutoSize = true;
        lblPendingValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblPendingValue.Location = new Point(274, 237);
        lblPendingValue.Name = "lblPendingValue";
        lblPendingValue.Size = new Size(24, 28);
        lblPendingValue.TabIndex = 11;
        lblPendingValue.Text = "0";
        lblRejectedValue.AutoSize = true;
        lblRejectedValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblRejectedValue.Location = new Point(274, 194);
        lblRejectedValue.Name = "lblRejectedValue";
        lblRejectedValue.Size = new Size(24, 28);
        lblRejectedValue.TabIndex = 10;
        lblRejectedValue.Text = "0";
        lblAcceptedValue.AutoSize = true;
        lblAcceptedValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblAcceptedValue.Location = new Point(274, 152);
        lblAcceptedValue.Name = "lblAcceptedValue";
        lblAcceptedValue.Size = new Size(24, 28);
        lblAcceptedValue.TabIndex = 9;
        lblAcceptedValue.Text = "0";
        lblTotalApplicationsValue.AutoSize = true;
        lblTotalApplicationsValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblTotalApplicationsValue.Location = new Point(274, 110);
        lblTotalApplicationsValue.Name = "lblTotalApplicationsValue";
        lblTotalApplicationsValue.Size = new Size(24, 28);
        lblTotalApplicationsValue.TabIndex = 8;
        lblTotalApplicationsValue.Text = "0";
        lblActiveJobsValue.AutoSize = true;
        lblActiveJobsValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblActiveJobsValue.Location = new Point(274, 68);
        lblActiveJobsValue.Name = "lblActiveJobsValue";
        lblActiveJobsValue.Size = new Size(24, 28);
        lblActiveJobsValue.TabIndex = 7;
        lblActiveJobsValue.Text = "0";
        lblTotalStudentsValue.AutoSize = true;
        lblTotalStudentsValue.Font = new Font("Segoe UI", 12F, FontStyle.Bold);
        lblTotalStudentsValue.Location = new Point(274, 26);
        lblTotalStudentsValue.Name = "lblTotalStudentsValue";
        lblTotalStudentsValue.Size = new Size(24, 28);
        lblTotalStudentsValue.TabIndex = 6;
        lblTotalStudentsValue.Text = "0";
        lblPending.AutoSize = true;
        lblPending.Location = new Point(26, 242);
        lblPending.Name = "lblPending";
        lblPending.Size = new Size(156, 20);
        lblPending.TabIndex = 5;
        lblPending.Text = "Pending Applications:";
        lblRejected.AutoSize = true;
        lblRejected.Location = new Point(26, 199);
        lblRejected.Name = "lblRejected";
        lblRejected.Size = new Size(160, 20);
        lblRejected.TabIndex = 4;
        lblRejected.Text = "Rejected Applications:";
        lblAccepted.AutoSize = true;
        lblAccepted.Location = new Point(26, 157);
        lblAccepted.Name = "lblAccepted";
        lblAccepted.Size = new Size(161, 20);
        lblAccepted.TabIndex = 3;
        lblAccepted.Text = "Accepted Applications:";
        lblTotalApplications.AutoSize = true;
        lblTotalApplications.Location = new Point(26, 115);
        lblTotalApplications.Name = "lblTotalApplications";
        lblTotalApplications.Size = new Size(131, 20);
        lblTotalApplications.TabIndex = 2;
        lblTotalApplications.Text = "Total Applications:";
        lblActiveJobs.AutoSize = true;
        lblActiveJobs.Location = new Point(26, 73);
        lblActiveJobs.Name = "lblActiveJobs";
        lblActiveJobs.Size = new Size(80, 20);
        lblActiveJobs.TabIndex = 1;
        lblActiveJobs.Text = "Active Jobs:";
        lblTotalStudents.AutoSize = true;
        lblTotalStudents.Location = new Point(26, 31);
        lblTotalStudents.Name = "lblTotalStudents";
        lblTotalStudents.Size = new Size(101, 20);
        lblTotalStudents.TabIndex = 0;
        lblTotalStudents.Text = "Total Students:";
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(877, 579);
        Controls.Add(tabMain);
        Controls.Add(lblWelcome);
        Name = "AdminDashboardForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Desktop Admin Dashboard";
        tabMain.ResumeLayout(false);
        tabJobs.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvJobs).EndInit();
        tabApplications.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvApplications).EndInit();
        tabReports.ResumeLayout(false);
        tabReports.PerformLayout();
        ResumeLayout(false);
    }
}
#nullable restore
