#nullable disable
namespace DesktopAdmin.Forms;

partial class JobEditForm
{
    private System.ComponentModel.IContainer components = null;
    private Label lblTitle;
    private Label lblDescription;
    private Label lblRequiredSkills;
    private Label lblLocation;
    private Label lblJobType;
    private TextBox txtTitle;
    private TextBox txtDescription;
    private TextBox txtRequiredSkills;
    private TextBox txtLocation;
    private ComboBox cmbJobType;
    private CheckBox chkIsActive;
    private Button btnSave;
    private Button btnCancel;
    private Label lblError;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components is not null)
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        lblTitle = new Label();
        lblDescription = new Label();
        lblRequiredSkills = new Label();
        lblLocation = new Label();
        lblJobType = new Label();
        txtTitle = new TextBox();
        txtDescription = new TextBox();
        txtRequiredSkills = new TextBox();
        txtLocation = new TextBox();
        cmbJobType = new ComboBox();
        chkIsActive = new CheckBox();
        btnSave = new Button();
        btnCancel = new Button();
        lblError = new Label();
        SuspendLayout();
        BackColor = Color.FromArgb(250, 252, 255);
        Font = new Font("Segoe UI", 9F);
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblTitle.ForeColor = Color.FromArgb(77, 88, 110);
        lblTitle.Location = new Point(30, 26);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(38, 20);
        lblTitle.TabIndex = 0;
        lblTitle.Text = "Title";
        txtTitle.BorderStyle = BorderStyle.FixedSingle;
        txtTitle.Font = new Font("Segoe UI", 10F);
        txtTitle.Location = new Point(150, 23);
        txtTitle.Name = "txtTitle";
        txtTitle.Size = new Size(275, 30);
        txtTitle.TabIndex = 1;
        lblDescription.AutoSize = true;
        lblDescription.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblDescription.ForeColor = Color.FromArgb(77, 88, 110);
        lblDescription.Location = new Point(30, 72);
        lblDescription.Name = "lblDescription";
        lblDescription.Size = new Size(85, 20);
        lblDescription.TabIndex = 2;
        lblDescription.Text = "Description";
        txtDescription.BorderStyle = BorderStyle.FixedSingle;
        txtDescription.Font = new Font("Segoe UI", 10F);
        txtDescription.Location = new Point(150, 69);
        txtDescription.Multiline = true;
        txtDescription.Name = "txtDescription";
        txtDescription.Size = new Size(275, 90);
        txtDescription.TabIndex = 3;
        lblRequiredSkills.AutoSize = true;
        lblRequiredSkills.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblRequiredSkills.ForeColor = Color.FromArgb(77, 88, 110);
        lblRequiredSkills.Location = new Point(30, 176);
        lblRequiredSkills.Name = "lblRequiredSkills";
        lblRequiredSkills.Size = new Size(102, 20);
        lblRequiredSkills.TabIndex = 4;
        lblRequiredSkills.Text = "Required Skills";
        txtRequiredSkills.BorderStyle = BorderStyle.FixedSingle;
        txtRequiredSkills.Font = new Font("Segoe UI", 10F);
        txtRequiredSkills.Location = new Point(150, 172);
        txtRequiredSkills.Name = "txtRequiredSkills";
        txtRequiredSkills.Size = new Size(275, 30);
        txtRequiredSkills.TabIndex = 5;
        lblLocation.AutoSize = true;
        lblLocation.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblLocation.ForeColor = Color.FromArgb(77, 88, 110);
        lblLocation.Location = new Point(30, 223);
        lblLocation.Name = "lblLocation";
        lblLocation.Size = new Size(64, 20);
        lblLocation.TabIndex = 6;
        lblLocation.Text = "Location";
        txtLocation.BorderStyle = BorderStyle.FixedSingle;
        txtLocation.Font = new Font("Segoe UI", 10F);
        txtLocation.Location = new Point(150, 219);
        txtLocation.Name = "txtLocation";
        txtLocation.Size = new Size(275, 30);
        txtLocation.TabIndex = 7;
        lblJobType.AutoSize = true;
        lblJobType.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblJobType.ForeColor = Color.FromArgb(77, 88, 110);
        lblJobType.Location = new Point(30, 270);
        lblJobType.Name = "lblJobType";
        lblJobType.Size = new Size(67, 20);
        lblJobType.TabIndex = 8;
        lblJobType.Text = "Job Type";
        cmbJobType.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbJobType.FormattingEnabled = true;
        cmbJobType.Location = new Point(150, 266);
        cmbJobType.Name = "cmbJobType";
        cmbJobType.Size = new Size(275, 28);
        cmbJobType.TabIndex = 9;
        chkIsActive.AutoSize = true;
        chkIsActive.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        chkIsActive.ForeColor = Color.FromArgb(77, 88, 110);
        chkIsActive.Location = new Point(150, 312);
        chkIsActive.Name = "chkIsActive";
        chkIsActive.Size = new Size(76, 24);
        chkIsActive.TabIndex = 10;
        chkIsActive.Text = "Active";
        chkIsActive.UseVisualStyleBackColor = true;
        btnSave.BackColor = Color.FromArgb(31, 119, 90);
        btnSave.Cursor = Cursors.Hand;
        btnSave.FlatAppearance.BorderSize = 0;
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnSave.ForeColor = Color.White;
        btnSave.Location = new Point(150, 355);
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(132, 40);
        btnSave.TabIndex = 11;
        btnSave.Text = "Save";
        btnSave.UseVisualStyleBackColor = false;
        btnSave.Click += btnSave_Click;
        btnCancel.BackColor = Color.White;
        btnCancel.Cursor = Cursors.Hand;
        btnCancel.FlatAppearance.BorderColor = Color.FromArgb(186, 196, 214);
        btnCancel.FlatStyle = FlatStyle.Flat;
        btnCancel.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        btnCancel.ForeColor = Color.FromArgb(52, 64, 92);
        btnCancel.Location = new Point(293, 355);
        btnCancel.Name = "btnCancel";
        btnCancel.Size = new Size(132, 40);
        btnCancel.TabIndex = 12;
        btnCancel.Text = "Cancel";
        btnCancel.UseVisualStyleBackColor = false;
        btnCancel.Click += btnCancel_Click;
        lblError.Font = new Font("Segoe UI", 9F, FontStyle.Bold);
        lblError.ForeColor = Color.FromArgb(196, 54, 44);
        lblError.Location = new Point(30, 406);
        lblError.Name = "lblError";
        lblError.Size = new Size(395, 34);
        lblError.TabIndex = 13;
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(458, 452);
        Controls.Add(lblError);
        Controls.Add(btnCancel);
        Controls.Add(btnSave);
        Controls.Add(chkIsActive);
        Controls.Add(cmbJobType);
        Controls.Add(lblJobType);
        Controls.Add(txtLocation);
        Controls.Add(lblLocation);
        Controls.Add(txtRequiredSkills);
        Controls.Add(lblRequiredSkills);
        Controls.Add(txtDescription);
        Controls.Add(lblDescription);
        Controls.Add(txtTitle);
        Controls.Add(lblTitle);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "JobEditForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Job";
        ResumeLayout(false);
        PerformLayout();
    }
}
#nullable restore
