namespace StudentInternshipJobPortal.DesktopAdmin.Forms;

partial class ManageJobsForm
{
    private System.ComponentModel.IContainer components = null!;
    private Label lblTitle = null!;
    private Label lblJobTitle = null!;
    private Label lblCompanyName = null!;
    private Label lblLocation = null!;
    private Label lblJobType = null!;
    private Label lblSkills = null!;
    private Label lblDescription = null!;
    private TextBox txtTitle = null!;
    private TextBox txtCompanyName = null!;
    private TextBox txtLocation = null!;
    private ComboBox cboJobType = null!;
    private TextBox txtRequiredSkills = null!;
    private TextBox txtDescription = null!;
    private CheckBox chkIsActive = null!;
    private Button btnNew = null!;
    private Button btnSave = null!;
    private Button btnDelete = null!;
    private DataGridView dgvJobs = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        lblTitle = new Label();
        lblJobTitle = new Label();
        lblCompanyName = new Label();
        lblLocation = new Label();
        lblJobType = new Label();
        lblSkills = new Label();
        lblDescription = new Label();
        txtTitle = new TextBox();
        txtCompanyName = new TextBox();
        txtLocation = new TextBox();
        cboJobType = new ComboBox();
        txtRequiredSkills = new TextBox();
        txtDescription = new TextBox();
        chkIsActive = new CheckBox();
        btnNew = new Button();
        btnSave = new Button();
        btnDelete = new Button();
        dgvJobs = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)dgvJobs).BeginInit();
        SuspendLayout();
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
        lblTitle.Location = new Point(29, 22);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(166, 37);
        lblTitle.TabIndex = 0;
        lblTitle.Text = "Manage Jobs";
        lblJobTitle.AutoSize = true;
        lblJobTitle.Location = new Point(31, 80);
        lblJobTitle.Name = "lblJobTitle";
        lblJobTitle.Size = new Size(64, 20);
        lblJobTitle.TabIndex = 1;
        lblJobTitle.Text = "Job Title";
        lblCompanyName.AutoSize = true;
        lblCompanyName.Location = new Point(31, 136);
        lblCompanyName.Name = "lblCompanyName";
        lblCompanyName.Size = new Size(116, 20);
        lblCompanyName.TabIndex = 3;
        lblCompanyName.Text = "Company Name";
        lblLocation.AutoSize = true;
        lblLocation.Location = new Point(31, 192);
        lblLocation.Name = "lblLocation";
        lblLocation.Size = new Size(66, 20);
        lblLocation.TabIndex = 5;
        lblLocation.Text = "Location";
        lblJobType.AutoSize = true;
        lblJobType.Location = new Point(31, 248);
        lblJobType.Name = "lblJobType";
        lblJobType.Size = new Size(69, 20);
        lblJobType.TabIndex = 7;
        lblJobType.Text = "Job Type";
        lblSkills.AutoSize = true;
        lblSkills.Location = new Point(31, 304);
        lblSkills.Name = "lblSkills";
        lblSkills.Size = new Size(103, 20);
        lblSkills.TabIndex = 9;
        lblSkills.Text = "Required Skills";
        lblDescription.AutoSize = true;
        lblDescription.Location = new Point(31, 360);
        lblDescription.Name = "lblDescription";
        lblDescription.Size = new Size(85, 20);
        lblDescription.TabIndex = 11;
        lblDescription.Text = "Description";
        txtTitle.Location = new Point(31, 103);
        txtTitle.Name = "txtTitle";
        txtTitle.Size = new Size(319, 27);
        txtTitle.TabIndex = 2;
        txtCompanyName.Location = new Point(31, 159);
        txtCompanyName.Name = "txtCompanyName";
        txtCompanyName.Size = new Size(319, 27);
        txtCompanyName.TabIndex = 4;
        txtLocation.Location = new Point(31, 215);
        txtLocation.Name = "txtLocation";
        txtLocation.Size = new Size(319, 27);
        txtLocation.TabIndex = 6;
        cboJobType.DropDownStyle = ComboBoxStyle.DropDownList;
        cboJobType.FormattingEnabled = true;
        cboJobType.Location = new Point(31, 271);
        cboJobType.Name = "cboJobType";
        cboJobType.Size = new Size(319, 28);
        cboJobType.TabIndex = 8;
        txtRequiredSkills.Location = new Point(31, 327);
        txtRequiredSkills.Name = "txtRequiredSkills";
        txtRequiredSkills.Size = new Size(319, 27);
        txtRequiredSkills.TabIndex = 10;
        txtDescription.Location = new Point(31, 383);
        txtDescription.Multiline = true;
        txtDescription.Name = "txtDescription";
        txtDescription.Size = new Size(319, 94);
        txtDescription.TabIndex = 12;
        chkIsActive.AutoSize = true;
        chkIsActive.Checked = true;
        chkIsActive.CheckState = CheckState.Checked;
        chkIsActive.Location = new Point(31, 491);
        chkIsActive.Name = "chkIsActive";
        chkIsActive.Size = new Size(77, 24);
        chkIsActive.TabIndex = 13;
        chkIsActive.Text = "Is Active";
        chkIsActive.UseVisualStyleBackColor = true;
        btnNew.Location = new Point(31, 532);
        btnNew.Name = "btnNew";
        btnNew.Size = new Size(92, 35);
        btnNew.TabIndex = 14;
        btnNew.Text = "New";
        btnNew.UseVisualStyleBackColor = true;
        btnNew.Click += BtnNew_Click;
        btnSave.BackColor = Color.FromArgb(13, 110, 253);
        btnSave.FlatAppearance.BorderSize = 0;
        btnSave.FlatStyle = FlatStyle.Flat;
        btnSave.ForeColor = Color.White;
        btnSave.Location = new Point(129, 532);
        btnSave.Name = "btnSave";
        btnSave.Size = new Size(105, 35);
        btnSave.TabIndex = 15;
        btnSave.Text = "Save";
        btnSave.UseVisualStyleBackColor = false;
        btnSave.Click += BtnSave_Click;
        btnDelete.BackColor = Color.FromArgb(220, 53, 69);
        btnDelete.FlatAppearance.BorderSize = 0;
        btnDelete.FlatStyle = FlatStyle.Flat;
        btnDelete.ForeColor = Color.White;
        btnDelete.Location = new Point(240, 532);
        btnDelete.Name = "btnDelete";
        btnDelete.Size = new Size(110, 35);
        btnDelete.TabIndex = 16;
        btnDelete.Text = "Delete";
        btnDelete.UseVisualStyleBackColor = false;
        btnDelete.Click += BtnDelete_Click;
        dgvJobs.AllowUserToAddRows = false;
        dgvJobs.AllowUserToDeleteRows = false;
        dgvJobs.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvJobs.BackgroundColor = Color.White;
        dgvJobs.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvJobs.Location = new Point(381, 80);
        dgvJobs.MultiSelect = false;
        dgvJobs.Name = "dgvJobs";
        dgvJobs.ReadOnly = true;
        dgvJobs.RowHeadersWidth = 51;
        dgvJobs.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvJobs.Size = new Size(678, 487);
        dgvJobs.TabIndex = 17;
        dgvJobs.SelectionChanged += DgvJobs_SelectionChanged;
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1092, 607);
        Controls.Add(dgvJobs);
        Controls.Add(btnDelete);
        Controls.Add(btnSave);
        Controls.Add(btnNew);
        Controls.Add(chkIsActive);
        Controls.Add(txtDescription);
        Controls.Add(txtRequiredSkills);
        Controls.Add(cboJobType);
        Controls.Add(txtLocation);
        Controls.Add(txtCompanyName);
        Controls.Add(txtTitle);
        Controls.Add(lblDescription);
        Controls.Add(lblSkills);
        Controls.Add(lblJobType);
        Controls.Add(lblLocation);
        Controls.Add(lblCompanyName);
        Controls.Add(lblJobTitle);
        Controls.Add(lblTitle);
        Name = "ManageJobsForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Manage Jobs";
        ((System.ComponentModel.ISupportInitialize)dgvJobs).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
}
